name: Send Discovered API to ApiConnect 

on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: apps.67e5e21a0fe7abc24ece31e7.am1.techzone.ibm.com
  # platform_api_prefix is not required to change for ApiConnect on Cloudd
  PLATFORM_API_PREFIX: apim-demo-mgmt-platform-api-tools
  PROVIDER_ORG: cp4i-demo-org
  INSECURE_SKIP_TLS_VERIFY: True
  #API_FILES: APIfolder/api-with-examples.yaml
  #API_FILES: apic-friendly-secure-import.json
  API_FILES: Test.json
  #API_FILES: FHIR.json
  #API_FOLDERS: APIfolderTwo
  APICAPIKEY: 899f68c9-71e7-4114-954b-8ff584438669

jobs:
  run-discovery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Difference
      id: difference-output
      run: |
        echo "action_updates=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
    - uses: ibm-apiconnect/apic-discovery-action@main
      id: discover-apis
      with:
        api_host: ${{ env.API_HOST }}
        platform_api_prefix: ${{ env.PLATFORM_API_PREFIX }}
        provider_org: ${{ env.PROVIDER_ORG }}
        insecure_skip_tls_verify: ${{ env.INSECURE_SKIP_TLS_VERIFY }}
        api_key: ${{ env.APICAPIKEY }}
        api_files: ${{ env.API_FILES }}
        api_folders: ${{ env.API_FOLDERS }}
        resync_check: ${{ true }}
        git_diff: ${{ steps.difference-output.outputs.action_updates }}
    - name: Display the action-result
      run: |
        echo "Result of the action: ${{ steps.discover-apis.outputs.action-result }}"
        echo "End"  
